version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  django:
    build:
      context: ./setup
      dockerfile: setup/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./webapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - django

volumes:
  postgres_data: