# Generated by Django 5.2 on 2025-09-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
